spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chapter3
    username: root
    password: admin
    driver-class-name: com.mysql.jdbc.Driver
    type: org.apache.commons.dbcp2.BasicDataSource
    dbcp2:
      #最大等待连接数量
      max-idle: 10
       #最大等待毫秒数
      max-wait-millis: 1000
      #最大连接活动数
      max-total: 20
      #数据库连接池初始化连接数
      initial-size: 5
  #Redis
  redis:
    jedis:
      pool:
        max-active: 10
        max-idle: 10
        max-wait: 2000ms
        min-idle: 5
    port: 6379
    host: 119.29.243.108
    password: admin
    timeout: 1000ms
mybatis:
  mapper-locations: classpath:com/springboot/springboot/chapter6/mapper/*.xml
  #MyBatis扫描别名包和注解@Alias联用
  type-aliases-package: com.springboot.springboot.chapter6.pojo
  #配置typeHandler的扫描包
  #type-handlers-package: com.springboot.springboot.chapter5.typehandler

#日志配置
logging:
  level: debug

